_target_: src.models.dual_graph_module.DualGraphModule
num_classes: 2
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00035367122046193675
  # lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.dual_graph_network.DualGraph
  embedding_checkpoint_path: './logs/train_diffusion_/runs/2024-01-14_20-27-22/checkpoints/last.ckpt'