# @package _global_

defaults:
  - _self_
  - data: pol_user_eval.yaml
  #- model: mnist.yaml
  - model: diffusion_eval.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]


ckpt_path: ./logs/train_diffusion_pol/runs/2024-01-13_11-54-10/checkpoints/last.ckpt


